# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('dept_abbr', models.CharField(max_length=15)),
                ('course_number', models.IntegerField()),
                ('student_count', models.IntegerField()),
                ('students_in_major', models.IntegerField()),
                ('popularity_rank', models.IntegerField()),
                ('course_full_name', models.CharField(max_length=100)),
                ('percentiles', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('iqr_min', models.DecimalField(decimal_places=2, max_digits=3)),
                ('q1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('median', models.DecimalField(decimal_places=2, max_digits=3)),
                ('q3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('iqr_max', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_abbr', models.CharField(max_length=15)),
                ('pathway', models.IntegerField(default=0)),
                ('campus', models.CharField(choices=[('seattle', 'Seattle Campus'), ('tacoma', 'Bothell Campus'), ('bothell', 'Tacoma Campus')], max_length=30)),
                ('college', models.CharField(max_length=100)),
                ('major_full_name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open Admission'), ('minimum', 'Minimum Requirements Admission'), ('capacity-constrained', 'Capacity-contrained Admission')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='gpa',
            name='major_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_gpas', to='pivot_v2.Major'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_courses', to='pivot_v2.Major'),
        ),
    ]
